### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jtokoph** [blockspring/blockspring-cli#1]
- [x] Get
  - [x] Not allowed?
  - [x] Block doesn't exist?
- [x] Push New
  - [x] Invalid language
  - [x] Missing files?
- [x] Push Update
  - [x] What if it fails, overwrite files?!?!
- [ ] ~~Delete?~~
- [ ] ~~Clone/fork (make a copy without the id)~~
- [x] Login
- [x] Logout
- [x] Run
  - [x] Set api key env var
  - [x] Run rest of args if command line (env/run)
  - [x] Run remote block without needing runtime (exec)
    - [x] Parse params/stdin or use library?
- [ ] New block generator
  - [x] Accept language and name
  - [x] Create block.lang and blockspring.js
  - [x] Create folder with slug of name
  - [x] Pull down hello world example for given language
  - [ ] Install library/generate package.json/requirement.txt/Gemfile
- [x] Add readme
### Known issues
- [x] We always sync files, even on error
  - [x] Only sync on success
  - [x] Only sync what needs to be synced
